services:
  app:
    build: .
    environment:
      DB_SERVER: "db"
      DB_USER: "SA"
      DB_PASSWORD: "Test1234"
      DB_PORT: "1433"
      DB_NAME: "TitDB"
      
      MQTT_PROTOCOL: "tcp"
      MQTT_SERVER: "broker"
      MQTT_PORT: "1883"

      HUB_SETTINGS_PATH: "/app/internal/adapters/mqtt/hub-settings.json"

      TELEGRAM_BOT_TOKEN: "yourBotToken"
      TELEGRAM_BOT_TARGET: "ChatIdNumber"
    links:
      - db
      - broker
  
  db:
    build: ./testdb/
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test1234"
    ports:
      - "1433:1433"

  broker:
    image: eclipse-mosquitto
    volumes:
      - ./testmqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"